// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Action     string             `db:"action" json:"action"`
	Resource   string             `db:"resource" json:"resource"`
	ResourceID pgtype.Text        `db:"resource_id" json:"resource_id"`
	OldValue   []byte             `db:"old_value" json:"old_value"`
	NewValue   []byte             `db:"new_value" json:"new_value"`
	IpAddress  *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent  pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Name         string             `db:"name" json:"name"`
	IsActive     pgtype.Bool        `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
