// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateUser(ctx context.Context, id pgtype.UUID) error
	CountUsers(ctx context.Context, isActive pgtype.Bool) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersPrev(ctx context.Context, arg ListUsersPrevParams) ([]User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
}

var _ Querier = (*Queries)(nil)
