package database

import (
	"context"
	"fmt"
	"time"

	"github.com/14mdzk/goscratch/internal/platform/config"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// DBTX is the interface satisfied by both *pgxpool.Pool and pgx.Tx.
// It matches the interface generated by SQLC.
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

// DBFromContext returns the transaction stored in ctx (if any), otherwise
// returns the pool. This allows repository methods to transparently participate
// in a transaction started by the usecase layer.
func DBFromContext(ctx context.Context, pool *pgxpool.Pool) DBTX {
	if tx := GetTx(ctx); tx != nil {
		return tx
	}
	return pool
}

// NewPostgresPool creates a new PostgreSQL connection pool
func NewPostgresPool(ctx context.Context, cfg config.DatabaseConfig) (*pgxpool.Pool, error) {
	poolCfg, err := pgxpool.ParseConfig(cfg.DSN())
	if err != nil {
		return nil, fmt.Errorf("failed to parse database config: %w", err)
	}

	// Configure pool settings
	poolCfg.MaxConns = int32(cfg.MaxOpenConns)
	poolCfg.MinConns = int32(cfg.MaxIdleConns)
	poolCfg.MaxConnLifetime = time.Duration(cfg.ConnMaxLifetime) * time.Second
	poolCfg.MaxConnIdleTime = 30 * time.Minute
	poolCfg.HealthCheckPeriod = 1 * time.Minute

	// Create pool
	pool, err := pgxpool.NewWithConfig(ctx, poolCfg)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection pool: %w", err)
	}

	// Test connection
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	return pool, nil
}

// txBeginner is the minimal subset of *pgxpool.Pool needed to start a
// transaction. It exists so unit tests can inject a fake pool / tx and
// exercise the rollback-context path without a live database.
type txBeginner interface {
	Begin(ctx context.Context) (pgx.Tx, error)
}

// Transactor provides transaction support
type Transactor struct {
	pool txBeginner
}

// NewTransactor creates a new transactor
func NewTransactor(pool *pgxpool.Pool) *Transactor {
	return &Transactor{pool: pool}
}

// TxFunc is a function that runs within a transaction
type TxFunc func(ctx context.Context) error

// WithTx executes a function within a database transaction
func (t *Transactor) WithTx(ctx context.Context, fn TxFunc) error {
	tx, err := t.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	// Store tx in context for repositories to use
	ctx = context.WithValue(ctx, txKey{}, tx)

	defer func() {
		if p := recover(); p != nil {
			// outer ctx may already be cancelled on shutdown; rollback must still run.
			rbCtx, cancel := context.WithTimeout(context.Background(), rollbackTimeout)
			defer cancel()
			_ = tx.Rollback(rbCtx)
			panic(p) // Re-throw panic after rollback
		}
	}()

	if err := fn(ctx); err != nil {
		// outer ctx may already be cancelled on shutdown; rollback must still run.
		rbCtx, cancel := context.WithTimeout(context.Background(), rollbackTimeout)
		defer cancel()
		if rbErr := tx.Rollback(rbCtx); rbErr != nil {
			return fmt.Errorf("tx error: %w, rollback error: %v", err, rbErr)
		}
		return err
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit transaction: %w", err)
	}

	return nil
}

// rollbackTimeout bounds how long a rollback is allowed to take when the outer
// context has already been cancelled (typically on shutdown). Without a fresh
// context the rollback would observe ctx.Err() immediately and never reach the
// database, leaking the in-flight transaction on the server.
const rollbackTimeout = 5 * time.Second

// txKey is the context key for transactions
type txKey struct{}

// GetTx retrieves the transaction from context, or nil if not in a transaction.
func GetTx(ctx context.Context) pgx.Tx {
	tx, _ := ctx.Value(txKey{}).(pgx.Tx)
	return tx
}
